name: agentpoison-hw
channels:
  - pytorch
  - defaults
  - anaconda
  - main
  - nvidia
  - conda-forge
dependencies:
  - python=3.9
  - cudatoolkit-dev=11.7
  - pip
  - spacy
  - spacy-model-en_core_web_sm=3.5.0
  - pip:
    - torch==2.0.1
    - torchaudio
    - torchvision
    - huggingface-hub==0.20.2
    - transformers==4.39.1
    - sentence-transformers
    - accelerate==0.26.1
    - wandb
    - openai
    - matplotlib==3.7.1
    - numpy==1.24.3
    - pandas==2.1.4
    - seaborn==0.13.1
    - tqdm==4.64.1
    - scikit-learn
    - jsonlines==4.0.0 

