name: agentpoison-hw
channels:
  - pytorch
  - defaults
  - anaconda
  - main
  - nvidia
  - conda-forge
dependencies:
  - python=3.9
  - cudatoolkit-dev=11.7
  - pip
  - spacy
  - spacy-model-en_core_web_sm=3.5.0
  - pip:
    - torch==2.0.1
    - torchaudio
    - torchvision
    - huggingface-hub==0.20.2
    - psutil==5.9.4
    - iopath
    - pyyaml==6.0
    - regex==2022.10.31
    - tokenizers==0.15.0
    - tqdm==4.64.1
    - transformers==4.39.1
    - timm==0.6.13
    - webdataset==0.2.48
    - omegaconf==2.3.0
    - decord==0.6.0
    - peft==0.2.0
    - sentence-transformers
    - gradio==3.47.1
    - accelerate==0.26.1
    - bitsandbytes==0.41.1
    - scikit-image
    - wandb
    - shortuuid
    - chardet
    - openai
    - moviepy-1.0.3
    # - autogen==1.0.16
    - jsonlines==3.1.0
    - matplotlib==3.7.1
    - numpy==1.24.3
    - pandas==2.1.4
    - pyautogen==0.2.0
    - seaborn==0.13.1
    - termcolor==2.4.0
    - wolframalpha==5.0.0
    - datasets
    - gym==0.26.2
    - tenacity==8.5.0
    - shapely==2.0.5
    - casadi==3.6.5
    - opencv-python==4.10.0.84
    - bs4

